language: python
python:
  - "3.5"
install:
  - pip install coveralls

script: python3 -m unittest coveralls/test_rpn.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report
after_success:
  - coveralls
